name: Validate

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  validate:
    name: Validate
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    strategy:
      fail-fast: true
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]

    steps:
      - name: Checkout respository
        uses: actions/checkout@v3

      - name: Enable corepack
        run: corepack enable

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Format
        run: pnpm run format:check

      - name: Lint
        run: pnpm run lint:check

      - name: Typecheck
        run: pnpm run types:check

      - name: Install playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Build app
        run: pnpm run build
        env:
          NUXT_PUBLIC_APP_BASE_URL: "http://localhost:3000"
          NUXT_PUBLIC_REDMINE_ID: "${{ vars.NUXT_PUBLIC_REDMINE_ID }}"
          NUXT_PUBLIC_TYPESENSE_API_KEY: "${{ vars.NUXT_PUBLIC_TYPESENSE_API_KEY }}"
          NUXT_PUBLIC_TYPESENSE_COLLECTION: "${{ vars.NUXT_PUBLIC_TYPESENSE_COLLECTION }}"
          NUXT_PUBLIC_TYPESENSE_HOST: "${{ vars.NUXT_PUBLIC_TYPESENSE_HOST }}"
          NUXT_PUBLIC_TYPESENSE_PORT: "${{ vars.NUXT_PUBLIC_TYPESENSE_PORT }}"
          NUXT_PUBLIC_TYPESENSE_PROTOCOL: "${{ vars.NUXT_PUBLIC_TYPESENSE_PROTOCOL }}"

      - name: Run e2e tests
        run: pnpm run test:e2e

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  build-deploy:
    if: ${{ github.event_name == 'push' }}
    needs: [validate]
    uses: ./.github/workflows/build-deploy.yml
